delete:
  description: Archive a Cloud Cost Management Account.
  operationId: DeleteCostAzureUCConfig
  parameters:
    - $ref: ../components/parameters/CloudAccountID.yaml
  responses:
    '204':
      description: No Content
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_write
  summary: Delete Cloud Cost Management Azure config
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_write
patch:
  description: Update the status of an  Azure config (active/archived).
  operationId: UpdateCostAzureUCConfigs
  parameters:
    - $ref: ../components/parameters/CloudAccountID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AzureUCConfigPatchRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AzureUCConfigPairsResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_write
  summary: Update Cloud Cost Management Azure config
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_write
