get:
  description: >-
    List tags and aggregations that are actively queried on dashboards,
    notebooks, monitors, the Metrics Explorer, and using the API for a given
    metric name.
  operationId: ListActiveMetricConfigurations
  parameters:
    - $ref: ../components/parameters/MetricName.yaml
    - description: >-
        The number of seconds of look back (from now).

        Default value is 604,800 (1 week), minimum value is 7200 (2 hours),
        maximum value is 2,630,000 (1 month).
      example: 7200
      in: query
      name: window[seconds]
      required: false
      schema:
        format: int64
        type: integer
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/MetricSuggestedTagsAndAggregationsResponse.yaml
      description: Success
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Too Many Requests
  summary: List active tags and aggregations
  tags:
    - Metrics
  x-permission:
    operator: OR
    permissions:
      - metrics_read
