delete:
  description: Delete an application key owned by this service account.
  operationId: DeleteServiceAccountApplicationKey
  parameters:
    - $ref: ../components/parameters/ServiceAccountID.yaml
    - $ref: ../components/parameters/ApplicationKeyID.yaml
  responses:
    '204':
      description: No Content
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete an application key for this service account
  tags:
    - Service Accounts
  x-permission:
    operator: OR
    permissions:
      - service_account_write
get:
  description: Get an application key owned by this service account.
  operationId: GetServiceAccountApplicationKey
  parameters:
    - $ref: ../components/parameters/ServiceAccountID.yaml
    - $ref: ../components/parameters/ApplicationKeyID.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PartialApplicationKeyResponse.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get one application key for this service account
  tags:
    - Service Accounts
  x-permission:
    operator: OR
    permissions:
      - service_account_write
patch:
  description: Edit an application key owned by this service account.
  operationId: UpdateServiceAccountApplicationKey
  parameters:
    - $ref: ../components/parameters/ServiceAccountID.yaml
    - $ref: ../components/parameters/ApplicationKeyID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationKeyUpdateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PartialApplicationKeyResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Edit an application key for this service account
  tags:
    - Service Accounts
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - service_account_write
