get:
  description: Get all incident types.
  operationId: ListIncidentTypes
  parameters:
    - $ref: ../components/parameters/IncidentTypeIncludeDeletedParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/IncidentTypeListResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - incident_read
  summary: Get a list of incident types
  tags:
    - Incidents
  x-permission:
    operator: OR
    permissions:
      - incident_read
  x-unstable: >-
    **Note**: This endpoint is in public beta.

    If you have any feedback, contact [Datadog
    support](https://docs.datadoghq.com/help/).
post:
  description: Create an incident type.
  operationId: CreateIncidentType
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/IncidentTypeCreateRequest.yaml
    description: Incident type payload.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/IncidentTypeResponse.yaml
      description: CREATED
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - incident_settings_write
  summary: Create an incident type
  tags:
    - Incidents
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - incident_settings_write
  x-unstable: >-
    **Note**: This endpoint is in public beta.

    If you have any feedback, contact [Datadog
    support](https://docs.datadoghq.com/help/).
