delete:
  description: Delete a specific security filter.
  operationId: DeleteSecurityFilter
  parameters:
    - $ref: ../components/parameters/SecurityFilterID.yaml
  responses:
    '204':
      description: OK
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - security_monitoring_filters_write
  summary: Delete a security filter
  tags:
    - Security Monitoring
  x-permission:
    operator: OR
    permissions:
      - security_monitoring_filters_write
get:
  description: >-
    Get the details of a specific security filter.


    See the [security filter
    guide](https://docs.datadoghq.com/security_platform/guide/how-to-setup-security-filters-using-security-monitoring-api/)

    for more examples.
  operationId: GetSecurityFilter
  parameters:
    - $ref: ../components/parameters/SecurityFilterID.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecurityFilterResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - security_monitoring_filters_read
  summary: Get a security filter
  tags:
    - Security Monitoring
  x-permission:
    operator: OR
    permissions:
      - security_monitoring_filters_read
patch:
  description: |-
    Update a specific security filter.
    Returns the security filter object when the request is successful.
  operationId: UpdateSecurityFilter
  parameters:
    - $ref: ../components/parameters/SecurityFilterID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SecurityFilterUpdateRequest.yaml
    description: New definition of the security filter.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecurityFilterResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '409':
      $ref: ../components/responses/ConcurrentModificationResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - security_monitoring_filters_write
  summary: Update a security filter
  tags:
    - Security Monitoring
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - security_monitoring_filters_write
