get:
  description: List all application keys available for your org
  operationId: ListApplicationKeys
  parameters:
    - $ref: ../components/parameters/PageSize.yaml
    - $ref: ../components/parameters/PageNumber.yaml
    - $ref: ../components/parameters/ApplicationKeysSortParameter.yaml
    - $ref: ../components/parameters/ApplicationKeyFilterParameter.yaml
    - $ref: >-
        ../components/parameters/ApplicationKeyFilterCreatedAtStartParameter.yaml
    - $ref: ../components/parameters/ApplicationKeyFilterCreatedAtEndParameter.yaml
    - $ref: ../components/parameters/ApplicationKeyIncludeParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ListApplicationKeysResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get all application keys
  tags:
    - Key Management
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_read
