delete:
  description: Delete a given archive from your organization.
  operationId: DeleteLogsArchive
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  responses:
    '204':
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete an archive
  tags:
    - Logs Archives
  x-permission:
    operator: OR
    permissions:
      - logs_write_archives
get:
  description: Get a specific archive from your organization.
  operationId: GetLogsArchive
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsArchive.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get an archive
  tags:
    - Logs Archives
  x-permission:
    operator: OR
    permissions:
      - logs_read_archives
put:
  description: >-
    Update a given archive configuration.


    **Note**: Using this method updates your archive configuration by
    **replacing**

    your current configuration with the new one sent to your Datadog
    organization.
  operationId: UpdateLogsArchive
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsArchiveCreateRequest.yaml
    description: New definition of the archive.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsArchive.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update an archive
  tags:
    - Logs Archives
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_write_archives
