post:
  description: >-
    Endpoint for uploading IdP metadata for SAML setup.


    Use this endpoint to upload or replace IdP metadata for SAML login
    configuration.
  operationId: UploadIdPMetadata
  requestBody:
    content:
      multipart/form-data:
        schema:
          $ref: ../components/schemas/IdPMetadataFormData.yaml
    required: true
  responses:
    '200':
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Upload IdP metadata
  tags:
    - Organizations
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - org_management
