get:
  description: List the AWS CUR configs.
  operationId: ListCostAWSCURConfigs
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AwsCURConfigsResponse.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_read
  summary: List Cloud Cost Management AWS CUR configs
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_read
post:
  description: Create a Cloud Cost Management account for an AWS CUR config.
  operationId: CreateCostAWSCURConfig
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AwsCURConfigPostRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AwsCURConfigResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_write
  summary: Create Cloud Cost Management AWS CUR config
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_write
