get:
  description: Get the list of RUM retention filters for a RUM application.
  operationId: ListRetentionFilters
  parameters:
    - $ref: ../components/parameters/RumApplicationIDParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/RumRetentionFiltersResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get all RUM retention filters
  tags:
    - Rum Retention Filters
post:
  description: >-
    Create a RUM retention filter for a RUM application.

    Returns RUM retention filter objects from the request body when the request
    is successful.
  operationId: CreateRetentionFilter
  parameters:
    - $ref: ../components/parameters/RumApplicationIDParameter.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/RumRetentionFilterCreateRequest.yaml
    description: The definition of the new RUM retention filter.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/RumRetentionFilterResponse.yaml
      description: Created
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create a RUM retention filter
  tags:
    - Rum Retention Filters
  x-codegen-request-body-name: body
