delete:
  description: >-
    Removes a role from an archive. ([Roles
    API](https://docs.datadoghq.com/api/v2/roles/))
  operationId: RemoveRoleFromArchive
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/RelationshipToRole.yaml
    required: true
  responses:
    '204':
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Revoke role from an archive
  tags:
    - Logs Archives
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_write_archives
get:
  description: Returns all read roles a given archive is restricted to.
  operationId: ListArchiveReadRoles
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/RolesResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: List read roles for an archive
  tags:
    - Logs Archives
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
post:
  description: >-
    Adds a read role to an archive. ([Roles
    API](https://docs.datadoghq.com/api/v2/roles/))
  operationId: AddReadRoleToArchive
  parameters:
    - $ref: ../components/parameters/ArchiveID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/RelationshipToRole.yaml
    required: true
  responses:
    '204':
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Grant role to an archive
  tags:
    - Logs Archives
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_write_archives
