get:
  description: |-
    Get the current order of your archives.
    This endpoint takes no JSON arguments.
  operationId: GetLogsArchiveOrder
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsArchiveOrder.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get archive order
  tags:
    - Logs Archives
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
put:
  description: >-
    Update the order of your archives. Since logs are processed sequentially,
    reordering an archive may change

    the structure and content of the data processed by other archives.


    **Note**: Using the `PUT` method updates your archive's order by replacing
    the current order

    with the new one.
  operationId: UpdateLogsArchiveOrder
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsArchiveOrder.yaml
    description: An object containing the new ordered list of archive IDs.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsArchiveOrder.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '422':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Unprocessable Entity
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update archive order
  tags:
    - Logs Archives
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_write_archives
