post:
  description: >-
    Create a scanning group.

    The request MAY include a configuration relationship.

    A rules relationship can be omitted entirely, but if it is included it MUST
    be

    null or an empty array (rules cannot be created at the same time).

    The new group will be ordered last within the configuration.
  operationId: CreateScanningGroup
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerGroupCreateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerCreateGroupResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create Scanning Group
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
