get:
  description: List the Azure configs.
  operationId: ListCostAzureUCConfigs
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AzureUCConfigsResponse.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_read
  summary: List Cloud Cost Management Azure configs
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_read
post:
  description: Create a Cloud Cost Management account for an Azure config.
  operationId: CreateCostAzureUCConfigs
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AzureUCConfigPostRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/AzureUCConfigPairsResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - cloud_cost_management_write
  summary: Create Cloud Cost Management Azure configs
  tags:
    - Cloud Cost Management
  x-permission:
    operator: OR
    permissions:
      - cloud_cost_management_write
