delete:
  description: Delete an application key
  operationId: DeleteApplicationKey
  parameters:
    - $ref: ../components/parameters/ApplicationKeyID.yaml
  responses:
    '204':
      description: No Content
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete an application key
  tags:
    - Key Management
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_write
get:
  description: Get an application key for your org.
  operationId: GetApplicationKey
  parameters:
    - $ref: ../components/parameters/ApplicationKeyID.yaml
    - $ref: ../components/parameters/ApplicationKeyIncludeParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get an application key
  tags:
    - Key Management
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_read
patch:
  description: Edit an application key
  operationId: UpdateApplicationKey
  parameters:
    - $ref: ../components/parameters/ApplicationKeyID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationKeyUpdateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Edit an application key
  tags:
    - Key Management
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_write
