delete:
  description: Delete a given rule.
  operationId: DeleteScanningRule
  parameters:
    - $ref: ../components/parameters/SensitiveDataScannerRuleID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerRuleDeleteRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerRuleDeleteResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete Scanning Rule
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
patch:
  description: >-
    Update a scanning rule.

    The request body MUST NOT include a standard_pattern relationship, as that
    relationship

    is non-editable. Trying to edit the regex attribute of a rule with a
    standard_pattern

    relationship will also result in an error.
  operationId: UpdateScanningRule
  parameters:
    - $ref: ../components/parameters/SensitiveDataScannerRuleID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerRuleUpdateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerRuleUpdateResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update Scanning Rule
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
