post:
  description: >-
    Create a scanning rule in a sensitive data scanner group, ordered last.

    The posted rule MUST include a group relationship.

    It MUST include either a standard_pattern relationship or a regex attribute,
    but not both.

    If included_attributes is empty or missing, we will scan all attributes
    except

    excluded_attributes. If both are missing, we will scan the whole event.
  operationId: CreateScanningRule
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerRuleCreateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerCreateRuleResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create Scanning Rule
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
