get:
  description: Get the list of configured log-based metrics with their definitions.
  operationId: ListLogsMetrics
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsMetricsResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get all log-based metrics
  tags:
    - Logs Metrics
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
post:
  description: >-
    Create a metric based on your ingested logs in your organization.

    Returns the log-based metric object from the request body when the request
    is successful.
  operationId: CreateLogsMetric
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsMetricCreateRequest.yaml
    description: The definition of the new log-based metric.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsMetricResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '409':
      $ref: ../components/responses/ConflictResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create a log-based metric
  tags:
    - Logs Metrics
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_generate_metrics
