get:
  description: Returns all standard patterns.
  operationId: ListStandardPatterns
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/SensitiveDataScannerStandardPatternsResponseData.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: List standard patterns
  tags:
    - Sensitive Data Scanner
  x-permission:
    operator: OR
    permissions:
      - data_scanner_read
