get:
  description: Returns all Org Configs (name, description, and value).
  operationId: ListOrgConfigs
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/OrgConfigListResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '401':
      $ref: ../components/responses/UnauthorizedResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: List Org Configs
  tags:
    - Organizations
  x-permission:
    operator: OPEN
    permissions: []
