delete:
  description: Delete a tenant-based handle from the Datadog Microsoft Teams integration.
  operationId: DeleteTenantBasedHandle
  parameters:
    - $ref: >-
        ../components/parameters/MicrosoftTeamsTenantBasedHandleIDPathParameter.yaml
  responses:
    '204':
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '412':
      $ref: ../components/responses/PreconditionFailedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete tenant-based handle
  tags:
    - Microsoft Teams Integration
get:
  description: >-
    Get the tenant, team, and channel information of a tenant-based handle from
    the Datadog Microsoft Teams integration.
  operationId: GetTenantBasedHandle
  parameters:
    - $ref: >-
        ../components/parameters/MicrosoftTeamsTenantBasedHandleIDPathParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MicrosoftTeamsTenantBasedHandleResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '412':
      $ref: ../components/responses/PreconditionFailedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get tenant-based handle information
  tags:
    - Microsoft Teams Integration
patch:
  description: Update a tenant-based handle from the Datadog Microsoft Teams integration.
  operationId: UpdateTenantBasedHandle
  parameters:
    - $ref: >-
        ../components/parameters/MicrosoftTeamsTenantBasedHandleIDPathParameter.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: >-
            ../components/schemas/MicrosoftTeamsUpdateTenantBasedHandleRequest.yaml
    description: Tenant-based handle payload.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MicrosoftTeamsTenantBasedHandleResponse.yaml
      description: OK
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '409':
      $ref: ../components/responses/ConflictResponse.yaml
    '412':
      $ref: ../components/responses/PreconditionFailedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update tenant-based handle
  tags:
    - Microsoft Teams Integration
  x-codegen-request-body-name: body
