put:
  description: Update a team permission setting for a given team.
  operationId: UpdateTeamPermissionSetting
  parameters:
    - description: None
      in: path
      name: team_id
      required: true
      schema:
        type: string
    - description: None
      in: path
      name: action
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/TeamPermissionSettingUpdateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TeamPermissionSettingResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: API error response.
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - teams_read
  summary: Update permission setting for team
  tags:
    - Teams
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - teams_read
