get:
  description: Get the list of configured rum-based metrics with their definitions.
  operationId: ListRumMetrics
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/RumMetricsResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get all rum-based metrics
  tags:
    - Rum Metrics
post:
  description: >-
    Create a metric based on your organization's RUM data.

    Returns the rum-based metric object from the request body when the request
    is successful.
  operationId: CreateRumMetric
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/RumMetricCreateRequest.yaml
    description: The definition of the new rum-based metric.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/RumMetricResponse.yaml
      description: Created
    '400':
      $ref: ../components/responses/BadRequestResponse.yaml
    '403':
      $ref: ../components/responses/NotAuthorizedResponse.yaml
    '409':
      $ref: ../components/responses/ConflictResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create a rum-based metric
  tags:
    - Rum Metrics
  x-codegen-request-body-name: body
