get:
  description: Get all permission settings for a given team.
  operationId: GetTeamPermissionSettings
  parameters:
    - description: None
      in: path
      name: team_id
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TeamPermissionSettingsResponse.yaml
      description: OK
    '403':
      $ref: ../components/responses/ForbiddenResponse.yaml
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: API error response.
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - teams_read
  summary: Get permission settings for a team
  tags:
    - Teams
  x-permission:
    operator: OR
    permissions:
      - teams_read
