delete:
  description: Delete a pipeline.
  operationId: DeletePipeline
  parameters:
    - description: The ID of the pipeline to delete.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  responses:
    '204':
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '409':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Conflict
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete a pipeline
  tags:
    - Observability Pipelines
  x-unstable: '**Note**: This endpoint is in Preview.'
get:
  description: Get a specific pipeline by its ID.
  operationId: GetPipeline
  parameters:
    - description: The ID of the pipeline to retrieve.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ObservabilityPipeline.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get a specific pipeline
  tags:
    - Observability Pipelines
  x-unstable: '**Note**: This endpoint is in Preview.'
put:
  description: Update a pipeline.
  operationId: UpdatePipeline
  parameters:
    - description: The ID of the pipeline to update.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ObservabilityPipeline.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ObservabilityPipeline.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '409':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Conflict
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update a pipeline
  tags:
    - Observability Pipelines
  x-unstable: '**Note**: This endpoint is in Preview.'
