delete:
  description: >-
    Delete all custom lists of queryable tag keys for a set of existing count,
    gauge, rate, and distribution metrics.

    Metrics are selected by passing a metric name prefix.

    Results can be sent to a set of account email addresses, just like the same
    operation in the Datadog web app.

    Can only be used with application keys of users with the `Manage Tags for
    Metrics` permission.
  operationId: DeleteBulkTagsMetricsConfiguration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/MetricBulkTagConfigDeleteRequest.yaml
    required: true
  responses:
    '202':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MetricBulkTagConfigResponse.yaml
      description: Accepted
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Too Many Requests
  summary: Delete tags for multiple metrics
  tags:
    - Metrics
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - metric_tags_write
post:
  description: >-
    Create and define a list of queryable tag keys for a set of existing count,
    gauge, rate, and distribution metrics.

    Metrics are selected by passing a metric name prefix. Use the Delete method
    of this API path to remove tag configurations.

    Results can be sent to a set of account email addresses, just like the same
    operation in the Datadog web app.

    If multiple calls include the same metric, the last configuration applied
    (not by submit order) is used, do not

    expect deterministic ordering of concurrent calls. The `exclude_tags_mode`
    value will set all metrics that match the prefix to

    the same exclusion state, metric tag configurations do not support mixed
    inclusion and exclusion for tags on the same metric.

    Can only be used with application keys of users with the `Manage Tags for
    Metrics` permission.
  operationId: CreateBulkTagsMetricsConfiguration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/MetricBulkTagConfigCreateRequest.yaml
    required: true
  responses:
    '202':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/MetricBulkTagConfigResponse.yaml
      description: Accepted
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Not Found
    '429':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Too Many Requests
  summary: Configure tags for multiple metrics
  tags:
    - Metrics
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - metric_tags_write
