delete:
  description: Delete a given group.
  operationId: DeleteScanningGroup
  parameters:
    - $ref: ../components/parameters/SensitiveDataScannerGroupID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerGroupDeleteRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerGroupDeleteResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete Scanning Group
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
patch:
  description: >-
    Update a group, including the order of the rules.

    Rules within the group are reordered by including a rules relationship. If
    the rules

    relationship is present, its data section MUST contain linkages for all of
    the rules

    currently in the group, and MUST NOT contain any others.
  operationId: UpdateScanningGroup
  parameters:
    - $ref: ../components/parameters/SensitiveDataScannerGroupID.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SensitiveDataScannerGroupUpdateRequest.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SensitiveDataScannerGroupUpdateResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication Error
    '404':
      $ref: ../components/responses/NotFoundResponse.yaml
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update Scanning Group
  tags:
    - Sensitive Data Scanner
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - data_scanner_write
