get:
  description: >-
    The Index object describes the configuration of a log index.

    This endpoint returns an array of the `LogIndex` objects of your
    organization.
  operationId: ListLogIndexes
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsIndexListResponse.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ: []
  summary: Get all indexes
  tags:
    - Logs Indexes
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
post:
  description: >-
    Creates a new index. Returns the Index object passed in the request body
    when the request is successful.
  operationId: CreateLogsIndex
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsIndex.yaml
    description: Object containing the new index.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsIndex.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsAPIErrorResponse.yaml
      description: Invalid Parameter Error
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create an index
  tags:
    - Logs Indexes
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_modify_indexes
