get:
  description: Get a list of all channels configured for your Datadog-Slack integration.
  operationId: GetSlackIntegrationChannels
  parameters:
    - $ref: ../components/parameters/SlackAccountNamePathParameter.yaml
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SlackIntegrationChannels.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Authentication error
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Item Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Get all channels in a Slack integration
  tags:
    - Slack Integration
  x-permission:
    operator: OR
    permissions:
      - integrations_read
post:
  description: Add a channel to your Datadog-Slack integration.
  operationId: CreateSlackIntegrationChannel
  parameters:
    - $ref: ../components/parameters/SlackAccountNamePathParameter.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SlackIntegrationChannel.yaml
    description: Payload describing Slack channel to be created
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SlackIntegrationChannel.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Authentication error
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Item Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Create a Slack integration channel
  tags:
    - Slack Integration
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - manage_integrations
