delete:
  description: |-
    Delete a given pipeline from your organization.
    This endpoint takes no JSON arguments.
  operationId: DeleteLogsPipeline
  parameters:
    - description: ID of the pipeline to delete.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  responses:
    '200':
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsAPIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Delete a pipeline
  tags:
    - Logs Pipelines
  x-permission:
    operator: OR
    permissions:
      - logs_write_pipelines
get:
  description: |-
    Get a specific pipeline from your organization.
    This endpoint takes no JSON arguments.
  operationId: GetLogsPipeline
  parameters:
    - description: ID of the pipeline to get.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsPipeline.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsAPIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Get a pipeline
  tags:
    - Logs Pipelines
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
put:
  description: >-
    Update a given pipeline configuration to change it’s processors or their
    order.


    **Note**: Using this method updates your pipeline configuration by
    **replacing**

    your current configuration with the new one sent to your Datadog
    organization.
  operationId: UpdateLogsPipeline
  parameters:
    - description: ID of the pipeline to delete.
      in: path
      name: pipeline_id
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsPipeline.yaml
    description: New definition of the pipeline.
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsPipeline.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsAPIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Update a pipeline
  tags:
    - Logs Pipelines
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_write_pipelines
