post:
  description: Creates an endpoint with the name `<WEBHOOK_NAME>`.
  operationId: CreateWebhooksIntegration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/WebhooksIntegration.yaml
    description: Create a webhooks integration request body.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/WebhooksIntegration.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication error
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  security:
    - apiKeyAuth: []
      appKeyAuth: []
    - AuthZ:
        - create_webhooks
  summary: Create a webhooks integration
  tags:
    - Webhooks Integration
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - create_webhooks
