get:
  description: >-
    Get the current order of your log indexes. This endpoint takes no JSON
    arguments.
  operationId: GetLogsIndexOrder
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsIndexesOrder.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Get indexes order
  tags:
    - Logs Indexes
  x-permission:
    operator: OR
    permissions:
      - logs_read_config
put:
  description: >-
    This endpoint updates the index order of your organization.

    It returns the index order object passed in the request body when the
    request is successful.
  operationId: UpdateLogsIndexOrder
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/LogsIndexesOrder.yaml
    description: Object containing the new ordered list of index names
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsIndexesOrder.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/LogsAPIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Update indexes order
  tags:
    - Logs Indexes
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - logs_modify_indexes
