post:
  description: Create a new service object in the PagerDuty integration.
  operationId: CreatePagerDutyIntegrationService
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/PagerDutyService.yaml
    description: Create a new service object request body.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PagerDutyServiceName.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Authentication error
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Create a new service object
  tags:
    - PagerDuty Integration
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - manage_integrations
