delete:
  description: Delete a given application key.
  operationId: DeleteApplicationKey_v1
  parameters:
    - description: The specific APP key you are working with.
      in: path
      name: key
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponsev1.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Delete an application key
  tags:
    - Key Management v1
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_write
      - user_app_keys
get:
  description: Get a given application key.
  operationId: GetApplicationKey_v1
  parameters:
    - description: The specific APP key you are working with.
      in: path
      name: key
      required: true
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponsev1.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Not Found
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Get an application key
  tags:
    - Key Management v1
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_read
      - user_app_keys
put:
  description: Edit an application key name.
  operationId: UpdateApplicationKey_v1
  parameters:
    - description: The specific APP key you are working with.
      in: path
      name: key
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationKey.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponsev1.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '404':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Not Found
    '409':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Conflict
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Edit an application key
  tags:
    - Key Management v1
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_write
      - user_app_keys
