get:
  description: Get all application keys available for your Datadog account.
  operationId: ListApplicationKeys_v1
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyListResponse.yaml
      description: OK
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Get all application keys
  tags:
    - Key Management v1
  x-permission:
    operator: OR
    permissions:
      - org_app_keys_read
      - user_app_keys
post:
  description: Create an application key with a given name.
  operationId: CreateApplicationKey_v1
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationKey.yaml
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationKeyResponsev1.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Forbidden
    '409':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponsev1.yaml
      description: Conflict
    '429':
      $ref: ../components/responses/TooManyRequestsResponsev1.yaml
  summary: Create an application key
  tags:
    - Key Management v1
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - user_app_keys
