post:
  description: Creates an endpoint with the name `<CUSTOM_VARIABLE_NAME>`.
  operationId: CreateWebhooksIntegrationCustomVariable
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/WebhooksIntegrationCustomVariable.yaml
    description: Define a custom variable request body.
    required: true
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/WebhooksIntegrationCustomVariableResponse.yaml
      description: OK
    '400':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Bad Request
    '403':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/APIErrorResponse.yaml
      description: Authentication error
    '429':
      $ref: ../components/responses/TooManyRequestsResponse.yaml
  summary: Create a custom variable
  tags:
    - Webhooks Integration
  x-codegen-request-body-name: body
  x-permission:
    operator: OR
    permissions:
      - manage_integrations
