description: The account filtering configuration.
properties:
  excluded_accounts:
    description: >-
      The AWS account IDs to be excluded from your billing dataset. This field
      is used when `include_new_accounts` is `true`.
    example:
      - '123456789123'
      - '123456789143'
    items:
      type: string
    type: array
  include_new_accounts:
    description: >-
      Whether or not to automatically include new member accounts by default in
      your billing dataset.
    example: true
    type: boolean
  included_accounts:
    description: >-
      The AWS account IDs to be included in your billing dataset. This field is
      used when `include_new_accounts` is `false`.
    example:
      - '123456789123'
      - '123456789143'
    items:
      type: string
    type: array
type: object
