description: Additional information related to the application key response.
properties:
  total_filtered_count:
    description: Total filtered application key count.
    format: int64
    type: integer
type: object
