description: Metadata associated with the WAF Custom Rule.
properties:
  added_at:
    description: The date and time the WAF custom rule was created.
    example: '2021-01-01T00:00:00Z'
    format: date-time
    type: string
  added_by:
    description: The handle of the user who created the WAF custom rule.
    example: john.doe@datadoghq.com
    type: string
  added_by_name:
    description: The name of the user who created the WAF custom rule.
    example: John Doe
    type: string
  modified_at:
    description: The date and time the WAF custom rule was last updated.
    example: '2021-01-01T00:00:00Z'
    format: date-time
    type: string
  modified_by:
    description: The handle of the user who last updated the WAF custom rule.
    example: john.doe@datadoghq.com
    type: string
  modified_by_name:
    description: The name of the user who last updated the WAF custom rule.
    example: John Doe
    type: string
readOnly: true
type: object
