description: Target WAF rules based either on an identifier or tags.
properties:
  rule_id:
    description: Target a single WAF rule based on its identifier.
    example: dog-913-009
    type: string
  tags:
    $ref: ./ApplicationSecurityWafExclusionFilterRulesTargetTags.yaml
type: object
