description: The definition of `ApplicationSecurityWafCustomRuleAction` object.
properties:
  action:
    $ref: ./ApplicationSecurityWafCustomRuleActionAction.yaml
  parameters:
    $ref: ./ApplicationSecurityWafCustomRuleActionParameters.yaml
type: object
