description: Object for creating a single WAF exclusion filter.
properties:
  attributes:
    $ref: ./ApplicationSecurityWafExclusionFilterCreateAttributes.yaml
  type:
    $ref: ./ApplicationSecurityWafExclusionFilterType.yaml
required:
  - attributes
  - type
type: object
