description: The scope of the WAF custom rule.
properties:
  data:
    description: >-
      Identifier of a list of data from the denylist. Can only be used as
      substitution from the list parameter.
    example: blocked_users
    type: string
  inputs:
    description: List of inputs on which at least one should match with the given operator.
    items:
      $ref: ./ApplicationSecurityWafCustomRuleConditionInput.yaml
    type: array
  list:
    description: >-
      List of value to use with the condition. Only used with the phrase_match,
      !phrase_match, exact_match and

      !exact_match operator.
    items:
      type: string
    type: array
  options:
    $ref: ./ApplicationSecurityWafCustomRuleConditionOptions.yaml
  regex:
    description: >-
      Regex to use with the condition. Only used with match_regex and
      !match_regex operator.
    example: path.*
    type: string
  value:
    description: >-
      Store the captured value in the specified tag name. Only used with the
      capture_data operator.
    example: custom_tag
    type: string
required:
  - inputs
type: object
