description: >-
  Unique Datadog ID of the AWS Account Integration Config.

  To get the config ID for an account, use the [List all AWS
  integrations](https://docs.datadoghq.com/api/latest/aws-integration/#list-all-aws-integrations)

  endpoint and query by AWS Account ID.
example: 00000000-abcd-0001-0000-000000000000
type: string
