description: AWS CUR config.
properties:
  attributes:
    $ref: ./AwsCURConfigAttributes.yaml
  id:
    description: The ID of the AWS CUR config.
    format: int64
    type: integer
  type:
    $ref: ./AwsCURConfigType.yaml
required:
  - attributes
  - type
type: object
