description: Attributes for AWS CUR config Post Request.
properties:
  account_filters:
    $ref: ./AccountFilteringConfig.yaml
  account_id:
    description: The AWS account ID.
    example: '123456789123'
    type: string
  bucket_name:
    description: The AWS bucket name used to store the Cost and Usage Report.
    example: dd-cost-bucket
    type: string
  bucket_region:
    description: The region the bucket is located in.
    example: us-east-1
    type: string
  is_enabled:
    description: Whether or not the Cloud Cost Management account is enabled.
    type: boolean
  months:
    description: The month of the report.
    format: int32
    maximum: 36
    type: integer
  report_name:
    description: The name of the Cost and Usage Report.
    example: dd-report-name
    type: string
  report_prefix:
    description: The report prefix used for the Cost and Usage Report.
    example: dd-report-prefix
    type: string
required:
  - account_id
  - bucket_name
  - report_name
  - report_prefix
type: object
