description: >-
  Log Autosubscription configuration for Datadog Forwarder Lambda functions.
  Automatically set up triggers for existing

  and new logs for some services, ensuring no logs from new resources are missed
  and saving time spent on manual configuration.
properties:
  lambdas:
    description: >-
      List of Datadog Lambda Log Forwarder ARNs in your AWS account. Defaults to
      `[]`.
    items:
      example: arn:aws:lambda:us-east-1:123456789012:function:DatadogLambdaLogForwarder
      type: string
    type: array
  sources:
    description: >-
      List of service IDs set to enable automatic log collection. Discover the
      list of available services with the

      [Get list of AWS log ready
      services](https://docs.datadoghq.com/api/latest/aws-logs-integration/#get-list-of-aws-log-ready-services)
      endpoint.
    items:
      example: s3
      type: string
    type: array
type: object
