description: AWS Resources Collection config.
properties:
  cloud_security_posture_management_collection:
    description: >-
      Enable Cloud Security Management to scan AWS resources for
      vulnerabilities, misconfigurations, identity risks, and compliance
      violations. Defaults to `false`. Requires `extended_collection` to be set
      to `true`.
    example: false
    type: boolean
  extended_collection:
    description: >-
      Whether Datadog collects additional attributes and configuration
      information about the resources in your AWS account. Defaults to `true`.
      Required for `cloud_security_posture_management_collection`.
    example: true
    type: boolean
type: object
