description: Azure config Patch data.
properties:
  attributes:
    $ref: ./AzureUCConfigPatchRequestAttributes.yaml
  type:
    $ref: ./AzureUCConfigPatchRequestType.yaml
required:
  - attributes
  - type
type: object
