description: The payload of a cloud configuration rule.
properties:
  cases:
    description: >
      Description of generated findings and signals (severity and channels to be
      notified in case of a signal). Must contain exactly one item.
    items:
      $ref: ./CloudConfigurationRuleCaseCreate.yaml
    type: array
  complianceSignalOptions:
    $ref: ./CloudConfigurationRuleComplianceSignalOptions.yaml
  filters:
    description: Additional queries to filter matched events before they are processed.
    items:
      $ref: ./SecurityMonitoringFilter.yaml
    type: array
  isEnabled:
    description: Whether the rule is enabled.
    example: true
    type: boolean
  message:
    description: Message in markdown format for generated findings and signals.
    example: |
      #Description
      Explanation of the rule.

      #Remediation
      How to fix the security issue.
    type: string
  name:
    description: The name of the rule.
    example: My security monitoring rule.
    type: string
  options:
    $ref: ./CloudConfigurationRuleOptions.yaml
  tags:
    description: Tags for generated findings and signals.
    example:
      - env:prod
      - team:security
    items:
      description: Tag.
      type: string
    type: array
  type:
    $ref: ./CloudConfigurationRuleType.yaml
required:
  - name
  - isEnabled
  - options
  - complianceSignalOptions
  - cases
  - message
type: object
