description: Configuration for a GCP metric namespace.
properties:
  disabled:
    default: false
    description: >-
      When disabled, Datadog does not collect metrics that are related to this
      GCP metric namespace.
    example: true
    type: boolean
  id:
    description: The id of the GCP metric namespace.
    example: aiplatform
    type: string
type: object
