description: Object containing the definition of a metric tag configuration to be updated.
properties:
  aggregations:
    $ref: ./MetricCustomAggregations.yaml
  exclude_tags_mode:
    description: >-
      When set to true, the configuration will exclude the configured tags and
      include any other submitted tags.

      When set to false, the configuration will include the configured tags and
      exclude any other submitted tags.

      Defaults to false. Requires `tags` property.
    type: boolean
  include_percentiles:
    description: >-
      Toggle to include/exclude percentiles for a distribution metric.

      Defaults to false. Can only be applied to metrics that have a
      `metric_type` of `distribution`.
    example: true
    type: boolean
  tags:
    default: []
    description: A list of tag keys that will be queryable for your metric.
    example:
      - app
      - datacenter
    items:
      description: Tag keys to group by.
      type: string
    type: array
type: object
