description: Optional parameters for bulk creating metric tag configurations.
properties:
  emails:
    $ref: ./MetricBulkTagConfigEmailList.yaml
  exclude_tags_mode:
    description: >-
      When set to true, the configuration will exclude the configured tags and
      include any other submitted tags.

      When set to false, the configuration will include the configured tags and
      exclude any other submitted tags.

      Defaults to false.
    type: boolean
  include_actively_queried_tags_window:
    description: |-
      When provided, all tags that have been actively queried are
      configured (and, therefore, remain queryable) for each metric that
      matches the given prefix.  Minimum value is 1 second, and maximum
      value is 7,776,000 seconds (90 days).
    format: double
    maximum: 7776000
    minimum: 1
    type: number
  override_existing_configurations:
    description: |-
      When set to true, the configuration overrides any existing
      configurations for the given metric with the new set of tags in this
      configuration request. If false, old configurations are kept and
      are merged with the set of tags in this configuration request.
      Defaults to true.
    type: boolean
  tags:
    $ref: ./MetricBulkTagConfigTagNameList.yaml
type: object
