description: >-
  Request object that includes the metric that you would like to configure tags
  for.
properties:
  data:
    $ref: ./MetricTagConfigurationCreateData.yaml
required:
  - data
type: object
