description: Policy and policy type for a monitor configuration policy.
properties:
  policy:
    $ref: ./MonitorConfigPolicyPolicy.yaml
  policy_type:
    $ref: ./MonitorConfigPolicyType.yaml
type: object
