description: Partial Datadog application key.
properties:
  attributes:
    $ref: ./PartialApplicationKeyAttributes.yaml
  id:
    description: ID of the application key.
    type: string
  relationships:
    $ref: ./ApplicationKeyRelationships.yaml
  type:
    $ref: ./ApplicationKeysType.yaml
type: object
