description: RUM application attributes.
properties:
  application_id:
    description: ID of the RUM application.
    example: abcd1234-0000-0000-abcd-1234abcd5678
    type: string
  client_token:
    description: Client token of the RUM application.
    example: abcd1234efgh5678ijkl90abcd1234efgh0
    type: string
  created_at:
    description: Timestamp in ms of the creation date.
    example: 1659479836169
    format: int64
    type: integer
  created_by_handle:
    description: Handle of the creator user.
    example: john.doe
    type: string
  hash:
    description: Hash of the RUM application. Optional.
    type: string
  is_active:
    description: Indicates if the RUM application is active.
    example: true
    type: boolean
  name:
    description: Name of the RUM application.
    example: my_rum_application
    type: string
  org_id:
    description: Org ID of the RUM application.
    example: 999
    format: int32
    maximum: 2147483647
    type: integer
  type:
    description: >-
      Type of the RUM application. Supported values are `browser`, `ios`,
      `android`, `react-native`, `flutter`, `roku`, `electron`, `unity`,
      `kotlin-multiplatform`.
    example: browser
    type: string
  updated_at:
    description: Timestamp in ms of the last update date.
    example: 1659479836169
    format: int64
    type: integer
  updated_by_handle:
    description: Handle of the updater user.
    example: jane.doe
    type: string
required:
  - application_id
  - client_token
  - created_at
  - created_by_handle
  - name
  - org_id
  - type
  - updated_at
  - updated_by_handle
type: object
