description: RUM application update.
properties:
  attributes:
    $ref: ./RUMApplicationUpdateAttributes.yaml
  id:
    description: RUM application ID.
    example: abcd1234-0000-0000-abcd-1234abcd5678
    type: string
  type:
    $ref: ./RUMApplicationUpdateType.yaml
required:
  - id
  - type
type: object
