description: Has one property enabled (boolean).
properties:
  enabled:
    description: >-
      Whether or not the SAML strict mode is enabled. If true, all users must
      log in with SAML.

      Learn more on the [SAML Strict
      documentation](https://docs.datadoghq.com/account_management/saml/#saml-strict).
    example: false
    type: boolean
type: object
