description: >-
  Set the boolean property enabled to enable or disable single sign on with
  SAML.

  See the SAML documentation for more information about all SAML settings.
properties:
  enabled:
    description: Whether or not SAML is enabled for this organization.
    example: false
    type: boolean
type: object
