description: Has one property enabled (boolean).
properties:
  enabled:
    description: >-
      Whether SAML IdP initiated login is enabled, learn more

      in the [SAML
      documentation](https://docs.datadoghq.com/account_management/saml/#idp-initiated-login).
    example: false
    type: boolean
type: object
