description: >-
  The RUM data collection settings for the Synthetic browser test.

  **Note:** There are 3 ways to format RUM settings:


  `{ isEnabled: false }`

  RUM data is not collected.


  `{ isEnabled: true }`

  RUM data is collected from the Synthetic test's default application.


  `{ isEnabled: true, applicationId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  clientTokenId: 12345 }`

  RUM data is collected using the specified application.
example:
  applicationId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  clientTokenId: 12345
  isEnabled: true
properties:
  applicationId:
    description: RUM application ID used to collect RUM data for the browser test.
    example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    type: string
  clientTokenId:
    description: RUM application API key ID used to collect RUM data for the browser test.
    example: 12345
    format: int64
    type: integer
  isEnabled:
    description: Determines whether RUM data is collected during test runs.
    example: true
    type: boolean
required:
  - isEnabled
type: object
