description: |-
  Application key attribute used to sort results. Sort order is ascending
  by default. In order to specify a descending sort, prefix the
  attribute with a minus sign.
in: query
name: sort
required: false
schema:
  $ref: ../schemas/ApplicationKeysSort.yaml
